- name: Converge
  hosts: all
  gather_facts: false
  strategy: linear
  vars:
    gluster_servers:
      - node-1.glusterfs.lab
      - node-2.glusterfs.lab
      - node-3.glusterfs.lab
  tasks:

    - name: Setup
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - 'distribution'

    - name: Include anwaryagoub.glusterfs role
      ansible.builtin.include_role:
        name: anwaryagoub.glusterfs_setup_cluster
